services:
  seed:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/scripts/docker-seed.sh"]
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ADMIN_DSN: ${ADMIN_DSN:-postgres://root:root@host.docker.internal:5432/root?sslmode=disable}
      ANILIST_DB: anilist
      MYANIMELIST_DB: myanimelist
      ANILIST_SORT: ID
      ENABLE_ANILIST_SEED: "true"
      ENABLE_MYANIMELIST_SEED: "false"
      FORCE_SEED: "false"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - go
      - run
      - ./cmd/api
      - --listen
      - :8081
      - --admin-dsn
      - ${ADMIN_DSN:-postgres://root:root@host.docker.internal:5432/root?sslmode=disable}
      - --anilist-dsn
      - ${ANILIST_DSN:-postgres://root:root@host.docker.internal:5432/anilist?sslmode=disable}
      - --myanimelist-dsn
      - ${MYANIMELIST_DSN:-postgres://root:root@host.docker.internal:5432/myanimelist?sslmode=disable}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8081"
